nelmio_api_doc:
    documentation:
        info:
            title: Eco Garden API
            description: Eco garden API's routes
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!_).* # Exclude routes starting with _